name: Build and Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm dependencies
        run: npm install

      - name: Create config.json
        env:
          CONF_JSON: ${{ secrets.CONF_JSON }}
        run: echo $CONF_JSON | base64 --decode > config.json

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist

      - name: Create release .zip
        run: |
          cd dist
          zip -r ../data_w.zip *
          cd ..
          ls
